export const STATE = {
  IS_SIGNED_IN: 'isSignedIn',
  DATA: 'data',
  VISIBLE_IN_LIST: 'visibleInList',
  TOGGLE_ON: 'toggleOn',
  IN_BUFFER: 'inBuffer',
  SELECTED: 'selected',
};

export const KEYS = {
  CAT: 'Category',
  FADD: '_Formatted_Address',
  LAT: 'Latitude',
  LONG: 'Longitude',
  INFO: 'Information',
  NAME: 'Name',
  // INFO: 'What is your estimated kitchen square footage? ', // change this obv
  // restaurant survey question fields:
  TIME_STAMP: 'Timestamp',
  EMAIL: 'Email Address',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  CONTACT_PHONE: 'Contact Phone Number ',
  REST_NAME: 'Restaurant Name',
  REST_ADDRESS: 'Address',
  REST_ZIP: 'Restaurant Zip Code ',
  PPE_ACCESS: 'Do you have access to the PPE in line with COVID-19 requirements?',
  FSR: 'What is your food safety rating?',
  TAKEOUT_OP: 'Are you operating takeout / delivery today?',
  DAILY_TAKEOUT_REVENUE: 'If you are operating takeout / delivery, how much revenue are you earning per day?',
  POS_USE: 'Do you use a digital POS (point of sale) system?',
  ONLINE_ORDER_CAPABILITY: 'Do you have an online order capability?',
  MEALS_PRODUCED_PER_DAY: 'What are the estimated number of meals you can produce per day?',
  MEALS_OUTPUT_PER_HOUR: 'What is your estimated meal output capacity per hour?',
  REFRIDG_CAPACITY: 'What is your estimated refrigeration capacity (i.e., how many meals can you keep cold at once)? ',
  SQ_FT: 'What is your estimated kitchen square footage? ',
  BOH_SINGLE_SHIFT: 'How many back of house kitchen staff are working per a single shift today?',
  BOH_PRE_COVID: 'How many back of house employees did you have pre-pandemic?',
  BOH_CURRENT: 'How many back of house employees do you have today?',
  MEAL_TYPE: 'Which type of meals do you serve?',
  AVG_PRE_COVID_COST_PCT: 'What is your average pre-COVID cost of goods sold (percentage)?',
  AVG_MENU_ITEM_PRICE: 'What is the average ticket price of your menu item meals? (food only, please round to the nearest dollar)',
  WKLY_SOLVENCY_COST: 'What are the estimated dollars per week you need to remain solvent? (note: this program is intended to be a stimulus, not a subsidy)',
  WKS_OPEN_NO_SUPPORT: 'How many weeks can you realistically stay open with no financial support? ',
  CARRY_OUT_FOOD_STYLE: 'What style of carry out food do you currently serve?',
  FOOD_SOURCE: 'How do you source the food for your restaurants?',
  SUPPLIERS_IN_OPS: 'Are your primary suppliers still operating (i.e., can you source ingredients for this effort?',
  DELIVERY: 'Are you able to provide delivery to food insecure populations? (incl. through third-party partners like Delivery.com, DoorDash, Uber Eats, etc.)',
  DIST_RELATIONSHIPS: 'Do you have relationships (e.g., community connections) that can be leveraged for food distribution? (delivery, volunteer distributors, etc.) ',
  SHARE_W_OTHER_RRP: 'Are you willing to share resources to other RRP partners as part of this program if necessary? ',
  NYC_AREA: 'In which NYC area is your restaurant(s) located? ',
  LOCS: 'How many NYC area locations do you have?',
  ADDL_LOC_ZIP_NYC: 'If you have more than one NYC restaurant, please enter the zip code(s) below (note: separate by comma)',
  ADDL_LOC_ZIP_OUTSIDE_NYC: 'If you have locations outside of the NYC area, where are they located? (note: separate by comma)',
  REST_TYPE: 'What type of restaurant are you?',
  CUISINE: 'What type of cuisine do you serve? (e.g., American, Chinese, Mexican, Greek, Italian, Turkish, Morrocan)',
  WOMAN_OWNED: 'Are you woman owned?',
  MINORITY_OWNED: 'Are you minority owned?',
  PURPOSE: 'What is your purpose / core values? ',
  COMM_GIVEBACK: 'How do you give back to the community? ',
  WHY_RETHINK: 'Why does Rethink Food’s cause matter to you? ',
  PPP: 'Have you received government-funded Payment Protection Program / CARES Act support?',
  PPP_EXPLAIN: 'If you have received government-funded Payment Protection Program / CARES Act support, please explain: ',
  OTHER_GOVT_FUNDING: 'Have you received other government grants / stimulus packages? ',
  OTHER_GOVT_FUNDING_EXPLAIN: 'If you have received other government grants / stimulus packages, please explain (e.g., $ amount, grant distributor, grant terms): ',
};

export default {};
